CLIENT:
  HOST: localhost
  PORT: 2000

WORLD:
  MAP: Town04
  FIXED_DELTA_SECONDS: 0.01

VEHICLE_ID: vehicle.mercedes.coupe_2020

SENSOR:
  LIDAR:
    MODEL: sensor.lidar.ray_cast
    LOCATION: [-0.5, 0.0, 1.8] 
    ROTATION: [0.0, 0.0, 0.0]
    UPPER_FOV: 22.5
    LOWER_FOV: -22.5
    CHANNELS: 64
    RANGE: 120
    ROTATION_FREQUENCY: 20
    POINTS_PER_SECOND: 2000000
    NOISE_STDDEV: 0.02
    SENSOR_TICK: 0.01
  IMU:
    NOISE_ACCEL_STDDEV_X: 0.0
    NOISE_ACCEL_STDDEV_Y: 0.0
    NOISE_ACCEL_STDDEV_Z: 0.0
    NOISE_GYRO_STDDEV_X: 0.0
    NOISE_GYRO_STDDEV_Y: 0.0
    NOISE_GYRO_STDDEV_Z: 0.0    
    SENSOR_TICK: 0.01
  GNSS:
    NOISE_ALT_STDDEV: 0.0
    NOISE_ALT_BIAS: 0.0
    NOISE_LAT_STDDEV: 0.0
    NOISE_LAT_BIAS: 0.0
    NOISE_LON_STDDEV: 0.0
    NOISE_LON_BIAS: 0.0
    SENSOR_TICK: 1.0

VOXEL_FILTER:
  RESOLUTION: 0.1